datastore:
  build: ./Datastore
rabbitmq:
  build: ./RabbitMQ
  env_file:
    - support/sensu.env
  volumes_from:
    - datastore
  ports:
    - "5671:5671"
redis:
  build: ./Redis
  env_file:
    - support/sensu.env
  volumes_from:
    - datastore
  links:
    - rabbitmq
  expose:
    - "6379"
sensu:
  build: ./Sensu
  env_file:
    - support/sensu.env
  environment:
    - SENSU_METRICS=false
  volumes_from:
    - datastore
  volumes:
    - /var/log/sensu:/var/log/sensu
    - /etc/sensu/conf.d:/etc/sensu/conf.d
  links:
    - redis
    - rabbitmq
  ports:
    - "3000:3000"
