rabbitmq:
  extends:
    file: common.yml
    service: rabbitmq
redis:
  extends:
    file: common.yml
    service: redis
  links:
    - rabbitmq
sensu:
  extends:
    file: common.yml
    service: sensu
  links:
    - redis
    - rabbitmq
