rabbitmq:
  build: ./RabbitMQ
  env_file:
    - /usr/local/etc/sensu-docker/sensu.env
  volumes:
    - /usr/local/etc/sensu-docker:/usr/local/etc/sensu-docker
  ports:
    - "5671:5671"
redis:
  build: ./Redis
  env_file:
    - /usr/local/etc/sensu-docker/sensu.env
  volumes:
    - /usr/local/etc/sensu-docker:/usr/local/etc/sensu-docker
  links:
    - rabbitmq
  expose:
    - "6379"
sensu:
  build: ./Sensu
  env_file:
    - /usr/local/etc/sensu-docker/sensu.env
  environment:
    - SENSU_METRICS=false
  volumes:
    - /usr/local/etc/sensu-docker:/usr/local/etc/sensu-docker
    - /var/log/sensu:/var/log/sensu
    - /etc/sensu/conf.d:/etc/sensu/conf.d
  links:
    - redis
    - rabbitmq
  ports:
    - "3000:3000"
