rabbitmq:
  build: ./RabbitMQ
  expose:
    - "5671"
redis:
  build: ./Redis
  links:
    - rabbitmq
  expose:
    - "6379"
sensu:
  build: ./Sensu
  volumes:
    - /var/log/sensu:/var/log/sensu
    - /etc/sensu/conf.d:/etc/sensu/conf.d
  links:
    - redis
    - rabbitmq
  ports:
    - "3000:3000"
